// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3VCFq1eV8M_16irKBCnOt6W571x8mWvY',
    appId: '1:297733501497:web:2a6247d6a09cdc487953e8',
    messagingSenderId: '297733501497',
    projectId: 'citofono-e2a73',
    authDomain: 'citofono-e2a73.firebaseapp.com',
    storageBucket: 'citofono-e2a73.firebasestorage.app',
    measurementId: 'G-L410BVHNPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehd4UjVyuWnfAklqQdwnKFfOmLSXP2h4',
    appId: '1:297733501497:android:03206cccf81f7adb7953e8',
    messagingSenderId: '297733501497',
    projectId: 'citofono-e2a73',
    storageBucket: 'citofono-e2a73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLvyBn0Hfg6eQo-LZFgE2WdgnC-zUgyA',
    appId: '1:297733501497:ios:e1b85dbbf85463b27953e8',
    messagingSenderId: '297733501497',
    projectId: 'citofono-e2a73',
    storageBucket: 'citofono-e2a73.firebasestorage.app',
    iosBundleId: 'com.gladiator.interfonia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKLvyBn0Hfg6eQo-LZFgE2WdgnC-zUgyA',
    appId: '1:297733501497:ios:71a6ad9794166b657953e8',
    messagingSenderId: '297733501497',
    projectId: 'citofono-e2a73',
    storageBucket: 'citofono-e2a73.firebasestorage.app',
    iosBundleId: 'com.example.citofonoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6WQ7M4dhQ-svKg8pY62E5HGn3l6BhcU',
    appId: '1:297733501497:web:ff431a3cd550c25c7953e8',
    messagingSenderId: '297733501497',
    projectId: 'citofono-e2a73',
    authDomain: 'citofono-e2a73.firebaseapp.com',
    storageBucket: 'citofono-e2a73.firebasestorage.app',
    measurementId: 'G-ELZSH62ESZ',
  );
}
